name: Terraform Deploy (dev & prod)

on:
  workflow_dispatch: {}          # run manually when you want
  push:
    branches: [ main ]
    paths:
      - "Environment/**"
      - "Modules/**"

permissions:
  contents: read

concurrency:
  group: terraform-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: deploy ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: dev
            chdir: Environment/dev
            tfvars: Environment/dev/terraform.tfvars
            gh_env: dev
          - env: prod
            chdir: Environment/prod
            tfvars: Environment/prod/terraform.tfvars
            gh_env: prod

    environment: ${{ matrix.gh_env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          client-id:        ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          tenant-id:        ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          subscription-id:  ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
          client-secret:    ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Export ARM vars for provider
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_USE_MSI=false" >> $GITHUB_ENV
          echo "ARM_USE_OIDC=false" >> $GITHUB_ENV

      - name: Terraform Init (Azure backend)
        working-directory: ${{ matrix.chdir }}
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=${{ vars.TF_STATE_RG }}" \
            -backend-config="storage_account_name=${{ vars.TF_STATE_SA }}" \
            -backend-config="container_name=${{ vars.TF_STATE_CONTAINER }}" \
            -backend-config="key=${{ matrix.env }}.tfstate"
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Terraform Plan
        working-directory: ${{ matrix.chdir }}
        run: terraform plan -input=false -no-color -var-file="${{ matrix.tfvars }}" -var="enforce_free=true" -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ matrix.chdir }}
        run: terraform apply -input=false -auto-approve tfplan
